name: testing_times
description: Demo code demonstrating use of async testing
version: 1.0.0
homepage: https://github.com/maks/testing_times

environment:
  sdk: '>=2.7.0 <3.0.0'


dependencies:
  rxdart: ^0.19.0
  

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.14.2
  quiver: ^2.1.3
  
  